name: C++ CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:

    runs-on: windows-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Install MSYS2
      uses: msys2/setup-msys2@v2
      with:
        update: true
        packages: >
          mingw-w64-x86_64-gcc
          mingw-w64-x86_64-make

    - name: Add MSYS2 to PATH
      run: |
        echo "C:\\msys64\\mingw64\\bin" >> $GITHUB_PATH

    - name: Build
      run: |
        mingw32-make

    - name: Run Tests
      run: |
        ./test_hangman.exe
